a = input("digite algo: ")
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaços ?', a.isspace())
print('Só tem números?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Está em maiúsculo?', a.isupper())
print('Está em minúsculo?', a.islower())
print('Está capitalizada?', a.istitle())
